GET http://localhost:8080

###

POST http://localhost:8080
Content-Type: application/json

{
  "query": "{countries{name}}"
}


###

POST https://countries.trevorblades.com
Content-Type: application/json

{
   "query": "{countries{name}}"
}
